/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Controller.DichVuController;
import DAO.DichVuDAO;
import DAO.LoaiDichVuDAO;
import POJO.DichVuPOJO;
import POJO.LoaiDichVuPOJO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DichVuJPanel extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form DichVuJPanel
     */
    ArrayList<String> maDVList;
    DichVuDAO dichVuDAO;
    LoaiDichVuDAO loaiDichVuDAO;
    DichVuController dichVuController;

    public DichVuJPanel() {
        initComponents();
        jtbDSDV.getTableHeader().setReorderingAllowed(false);
        loadDichVu();
        loadLoaiDV();
        customJTF();
        jtbDSDV.getTableHeader().setReorderingAllowed(false);
        dichVuController = new DichVuController(this);
        dichVuController.showDichVuView();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void customJTF() {
        FocusListener highlighter;
        highlighter = new FocusListener() {
            public void focusGained(FocusEvent e) {
                e.getComponent().setBackground(new Color(153, 255, 153));
            }

            public void focusLost(FocusEvent e) {
                e.getComponent().setBackground(UIManager.getColor("TextField.background"));
            }
        };
        jtfTenDV.addFocusListener(highlighter);
        jtfDonGia.addFocusListener(highlighter);
        jtfTuKhoa.addFocusListener(highlighter);
        jcbLoaiDV.addFocusListener(highlighter);

    }

    public void loadDichVu() {
        dichVuDAO = new DichVuDAO();
        maDVList = new ArrayList<>(); // Danh sách để lưu "Mã Dịch Vụ"
        // Tạo một đối tượng DefaultTableModel để chứa dữ liệu cho bảng
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Tên Dịch Vụ", "Loại Dịch Vụ", "Đơn Giá"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ArrayList<DichVuPOJO> DSDV = dichVuDAO.dsDV();

        for (DichVuPOJO dv : DSDV) {
            String maDV = "DV" + dv.getMaDV().toString();
            maDVList.add(maDV); // Thêm "Mã Dịch Vụ" vào danh sách
            model.addRow(new Object[]{dv.getTenDV(), dv.getTenLoaiDV(), dv.getDonGia()});
        }

        jtbDSDV.setModel(model);
    }

    public void loadLoaiDV() {
        loaiDichVuDAO = new LoaiDichVuDAO();
        ArrayList<LoaiDichVuPOJO> dsldv = loaiDichVuDAO.dsQuanHuyen();

        jcbLoaiDV.removeAllItems();

        for (LoaiDichVuPOJO ldv : dsldv) {
            jcbLoaiDV.addItem(ldv);
        }
    }

    public void fillText() {
        int row = jtbDSDV.getSelectedRow();
        if (row != -1) {
            jtfMaDV.setText(maDVList.get(row)); // Sử dụng maDVList giống như maKHList trong KhachHang
            jtfTenDV.setText((String) jtbDSDV.getValueAt(row, 0));
            String tenloaidv = (String) jtbDSDV.getValueAt(row, 1);
            for (int i = 0; i < jcbLoaiDV.getItemCount(); i++) {
                LoaiDichVuPOJO item = (LoaiDichVuPOJO) jcbLoaiDV.getItemAt(i);
                if (item.getTenLoaiDV().equals(tenloaidv)) {
                    jcbLoaiDV.setSelectedItem(item);
                    break;
                }
            }
            jtfDonGia.setText(String.valueOf(jtbDSDV.getValueAt(row, 2)));
        }
    }

    public void setEnabled() {
        jtfDonGia.setEnabled(false);
        jtfMaDV.setEnabled(false);
        jtfTenDV.setEnabled(false);
        jcbLoaiDV.setEnabled(false);
    }

    public void setAbled(String action) {
        if (action == "Them" || action == "CapNhat") {
            jtfDonGia.setEnabled(true);
            jtfMaDV.setEnabled(false);
            jtfTenDV.setEnabled(true);
            jcbLoaiDV.setEnabled(true);
        }
    }

    public void reset() {
        jtfDonGia.setText("");
        jtfMaDV.setText("");
        jtfTuKhoa.setText("");
        jtfTenDV.setText("");
        loadDichVu();
    }

    public boolean isEmpty() {
        if (jtfTenDV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tên bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
            jtfTenDV.requestFocus();
            return false;
        }
        if (jtfDonGia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Đơn giá bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
            jtfDonGia.requestFocus();
            return false;
        }
        if (Double.parseDouble(jtfDonGia.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "Giá trị đơn giá không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            jtfDonGia.requestFocus();
            return false;
        }
        return true;
    }

    public void capNhatDanhSachDV(ArrayList<DichVuPOJO> danhSachDV) {
        DefaultTableModel model = (DefaultTableModel) jtbDSDV.getModel();
        model.setRowCount(0); // Xóa tất cả các hàng hiện có
        for (DichVuPOJO dv : danhSachDV) {
            model.addRow(new Object[]{dv.getTenDV(), dv.getTenLoaiDV(), dv.getDonGia()});
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfMaDV = new javax.swing.JTextField();
        jtfDonGia = new javax.swing.JTextField();
        jtfTenDV = new javax.swing.JTextField();
        jcbLoaiDV = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jbtAdd = new javax.swing.JButton();
        jbtDel = new javax.swing.JButton();
        jbtUpd = new javax.swing.JButton();
        jbtSave = new javax.swing.JButton();
        jbtReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfTuKhoa = new javax.swing.JTextField();
        jbtSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDSDV = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1560, 992));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true), "THÔNG TIN DỊCH VỤ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã Dịch Vụ");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Loại Dịch Vụ");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Đơn Giá");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tên Dịch Vụ");

        jtfMaDV.setBackground(new java.awt.Color(255, 255, 255));
        jtfMaDV.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtfMaDV.setForeground(new java.awt.Color(0, 0, 0));

        jtfDonGia.setBackground(new java.awt.Color(255, 255, 255));
        jtfDonGia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtfDonGia.setForeground(new java.awt.Color(0, 0, 0));

        jtfTenDV.setBackground(new java.awt.Color(255, 255, 255));
        jtfTenDV.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtfTenDV.setForeground(new java.awt.Color(0, 0, 0));

        jcbLoaiDV.setBackground(new java.awt.Color(255, 255, 255));
        jcbLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbLoaiDV.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDonGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jcbLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true), "CHỨC NĂNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jbtAdd.setBackground(new java.awt.Color(255, 255, 255));
        jbtAdd.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtAdd.setForeground(new java.awt.Color(0, 0, 0));
        jbtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jbtAdd.setText("  Thêm");
        jbtAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jbtDel.setBackground(new java.awt.Color(255, 255, 255));
        jbtDel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtDel.setForeground(new java.awt.Color(0, 0, 0));
        jbtDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        jbtDel.setText("  Xóa");
        jbtDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtDel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jbtUpd.setBackground(new java.awt.Color(255, 255, 255));
        jbtUpd.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtUpd.setForeground(new java.awt.Color(0, 0, 0));
        jbtUpd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        jbtUpd.setText("  Sửa");
        jbtUpd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jbtSave.setBackground(new java.awt.Color(255, 255, 255));
        jbtSave.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtSave.setForeground(new java.awt.Color(0, 0, 0));
        jbtSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        jbtSave.setText("Lưu");

        jbtReset.setBackground(new java.awt.Color(255, 255, 255));
        jbtReset.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtReset.setForeground(new java.awt.Color(0, 0, 0));
        jbtReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/restart.png"))); // NOI18N
        jbtReset.setText("Làm mới");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Từ khóa:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtfTuKhoa.setBackground(new java.awt.Color(255, 255, 255));
        jtfTuKhoa.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtfTuKhoa.setForeground(new java.awt.Color(0, 0, 0));

        jbtSearch.setBackground(new java.awt.Color(255, 255, 255));
        jbtSearch.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtSearch.setForeground(new java.awt.Color(0, 0, 0));
        jbtSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jbtSearch.setText("Tìm kiếm");
        jbtSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jbtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jbtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jbtUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jbtReset)
                .addGap(44, 44, 44)
                .addComponent(jbtSave, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSearch)
                .addGap(69, 69, 69))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSave, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtReset, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(51, 153, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true), "DANH SÁCH DỊCH VỤ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jtbDSDV.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtbDSDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDSDV.setGridColor(new java.awt.Color(0, 0, 0));
        jtbDSDV.setRowHeight(50);
        jtbDSDV.setRowMargin(10);
        jScrollPane1.setViewportView(jtbDSDV);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("QUẢN LÝ DỊCH VỤ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtDel;
    private javax.swing.JButton jbtReset;
    private javax.swing.JButton jbtSave;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JButton jbtUpd;
    private javax.swing.JComboBox<LoaiDichVuPOJO> jcbLoaiDV;
    private javax.swing.JTable jtbDSDV;
    private javax.swing.JTextField jtfDonGia;
    private javax.swing.JTextField jtfMaDV;
    private javax.swing.JTextField jtfTenDV;
    private javax.swing.JTextField jtfTuKhoa;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void addJbtThemActionListener(ActionListener actionListener) {
        jbtAdd.addActionListener(actionListener);
    }

    public void addJbtXoaActionListener(ActionListener actionListener) {
        jbtDel.addActionListener(actionListener);
    }

    public void addJbtSuaActionListener(ActionListener actionListener) {
        jbtUpd.addActionListener(actionListener);
    }

    public void addJbtLuuActionListener(ActionListener actionListener) {
        jbtSave.addActionListener(actionListener);
    }

    public void addJbtResetActionListener(ActionListener actionListener) {
        jbtReset.addActionListener(actionListener);
    }

    public void addJbtSearchActionListener(ActionListener actionListener) {
        jbtSearch.addActionListener(actionListener);
    }

    public void addJtbDVSelectionListener(ListSelectionListener listener) {
        jtbDSDV.getSelectionModel().addListSelectionListener(listener);
    }

    public JComboBox<LoaiDichVuPOJO> getJcbLoaiDV() {
        return jcbLoaiDV;
    }

    public void setJcbLoaiDV(JComboBox<LoaiDichVuPOJO> jcbLoaiDV) {
        this.jcbLoaiDV = jcbLoaiDV;
    }

    public JTable getJtbDSDV() {
        return jtbDSDV;
    }

    public void setJtbDSDV(JTable jtbDSDV) {
        this.jtbDSDV = jtbDSDV;
    }

    public JTextField getJtfDonGia() {
        return jtfDonGia;
    }

    public void setJtfDonGia(JTextField jtfDonGia) {
        this.jtfDonGia = jtfDonGia;
    }

    public JTextField getJtfMaDV() {
        return jtfMaDV;
    }

    public void setJtfMaDV(JTextField jtfMaDV) {
        this.jtfMaDV = jtfMaDV;
    }

    public JTextField getJtfTenDV() {
        return jtfTenDV;
    }

    public void setJtfTenDV(JTextField jtfTenDV) {
        this.jtfTenDV = jtfTenDV;
    }

    public JTextField getJtfTuKhoa() {
        return jtfTuKhoa;
    }

    public void setJtfTuKhoa(JTextField jtfTuKhoa) {
        this.jtfTuKhoa = jtfTuKhoa;
    }
}
